# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Complex_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 531, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_25.setGeometry(QtCore.QRect(290, 20, 191, 181))
        self.groupBox_25.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_25.setObjectName("groupBox_25")
        self.screen_output_4 = QtWidgets.QTextEdit(self.groupBox_25)
        self.screen_output_4.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_4.setFont(font)
        self.screen_output_4.setObjectName("screen_output_4")
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_26.setGeometry(QtCore.QRect(290, 230, 191, 181))
        self.groupBox_26.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_26.setObjectName("groupBox_26")
        self.screen_output_6 = QtWidgets.QTextEdit(self.groupBox_26)
        self.screen_output_6.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_6.setFont(font)
        self.screen_output_6.setObjectName("screen_output_6")
        self.groupBox_27 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_27.setGeometry(QtCore.QRect(290, 440, 191, 181))
        self.groupBox_27.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_27.setObjectName("groupBox_27")
        self.screen_output_9 = QtWidgets.QTextEdit(self.groupBox_27)
        self.screen_output_9.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_9.setFont(font)
        self.screen_output_9.setObjectName("screen_output_9")
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_28.setGeometry(QtCore.QRect(50, 20, 191, 181))
        self.groupBox_28.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_28.setObjectName("groupBox_28")
        self.screen_output_10 = QtWidgets.QTextEdit(self.groupBox_28)
        self.screen_output_10.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_10.setFont(font)
        self.screen_output_10.setObjectName("screen_output_10")
        self.groupBox_29 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_29.setGeometry(QtCore.QRect(50, 230, 191, 181))
        self.groupBox_29.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_29.setObjectName("groupBox_29")
        self.screen_output_11 = QtWidgets.QTextEdit(self.groupBox_29)
        self.screen_output_11.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_11.setFont(font)
        self.screen_output_11.setObjectName("screen_output_11")
        self.groupBox_30 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_30.setGeometry(QtCore.QRect(50, 440, 191, 181))
        self.groupBox_30.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_30.setObjectName("groupBox_30")
        self.screen_output_12 = QtWidgets.QTextEdit(self.groupBox_30)
        self.screen_output_12.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_12.setFont(font)
        self.screen_output_12.setObjectName("screen_output_12")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_18.setGeometry(QtCore.QRect(50, 440, 191, 181))
        self.groupBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_18.setObjectName("groupBox_18")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_18)
        self.groupBox_22.setGeometry(QtCore.QRect(40, 20, 120, 80))
        self.groupBox_22.setObjectName("groupBox_22")
        self.spinBox_10 = QtWidgets.QSpinBox(self.groupBox_22)
        self.spinBox_10.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_10.setProperty("value", 85)
        self.spinBox_10.setObjectName("spinBox_10")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_18)
        self.groupBox_21.setGeometry(QtCore.QRect(40, 100, 120, 80))
        self.groupBox_21.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_21.setObjectName("groupBox_21")
        self.spinBox_9 = QtWidgets.QSpinBox(self.groupBox_21)
        self.spinBox_9.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_9.setProperty("value", 75)
        self.spinBox_9.setObjectName("spinBox_9")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_13.setGeometry(QtCore.QRect(50, 20, 191, 181))
        self.groupBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_13.setObjectName("groupBox_13")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 20, 120, 80))
        self.groupBox_7.setObjectName("groupBox_7")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox.setProperty("value", 81)
        self.spinBox.setObjectName("spinBox")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 100, 120, 80))
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_2.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_2.setProperty("value", 71)
        self.spinBox_2.setObjectName("spinBox_2")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_16.setGeometry(QtCore.QRect(290, 20, 191, 181))
        self.groupBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_16.setObjectName("groupBox_16")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_10.setGeometry(QtCore.QRect(40, 20, 120, 80))
        self.groupBox_10.setObjectName("groupBox_10")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_10)
        self.spinBox_4.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_4.setProperty("value", 82)
        self.spinBox_4.setObjectName("spinBox_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_9.setGeometry(QtCore.QRect(40, 100, 120, 80))
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setObjectName("groupBox_9")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_3.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_3.setProperty("value", 72)
        self.spinBox_3.setObjectName("spinBox_3")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_17.setGeometry(QtCore.QRect(50, 230, 191, 181))
        self.groupBox_17.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_17.setObjectName("groupBox_17")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 20, 120, 80))
        self.groupBox_12.setObjectName("groupBox_12")
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_12)
        self.spinBox_6.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_6.setProperty("value", 83)
        self.spinBox_6.setObjectName("spinBox_6")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 100, 120, 80))
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_11)
        self.spinBox_5.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_5.setProperty("value", 73)
        self.spinBox_5.setObjectName("spinBox_5")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_14.setGeometry(QtCore.QRect(290, 230, 191, 181))
        self.groupBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_14.setObjectName("groupBox_14")
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_20.setGeometry(QtCore.QRect(30, 20, 120, 80))
        self.groupBox_20.setObjectName("groupBox_20")
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_20)
        self.spinBox_8.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_8.setProperty("value", 84)
        self.spinBox_8.setObjectName("spinBox_8")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_19.setGeometry(QtCore.QRect(30, 100, 120, 80))
        self.groupBox_19.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_19.setObjectName("groupBox_19")
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_19)
        self.spinBox_7.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_7.setProperty("value", 74)
        self.spinBox_7.setObjectName("spinBox_7")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_15.setGeometry(QtCore.QRect(290, 440, 191, 181))
        self.groupBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_24.setGeometry(QtCore.QRect(40, 20, 120, 80))
        self.groupBox_24.setObjectName("groupBox_24")
        self.spinBox_14 = QtWidgets.QSpinBox(self.groupBox_24)
        self.spinBox_14.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_14.setProperty("value", 86)
        self.spinBox_14.setObjectName("spinBox_14")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_23.setGeometry(QtCore.QRect(40, 100, 120, 80))
        self.groupBox_23.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_23.setObjectName("groupBox_23")
        self.spinBox_13 = QtWidgets.QSpinBox(self.groupBox_23)
        self.spinBox_13.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.spinBox_13.setProperty("value", 76)
        self.spinBox_13.setObjectName("spinBox_13")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(50, 20, 191, 181))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.screen_output_1 = QtWidgets.QTextEdit(self.groupBox)
        self.screen_output_1.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_1.setFont(font)
        self.screen_output_1.setObjectName("screen_output_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 20, 191, 181))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.screen_output_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.screen_output_2.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_2.setFont(font)
        self.screen_output_2.setObjectName("screen_output_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 230, 191, 181))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.screen_output_3 = QtWidgets.QTextEdit(self.groupBox_3)
        self.screen_output_3.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_3.setFont(font)
        self.screen_output_3.setObjectName("screen_output_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(290, 230, 191, 181))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.screen_output_5 = QtWidgets.QTextEdit(self.groupBox_4)
        self.screen_output_5.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_5.setFont(font)
        self.screen_output_5.setObjectName("screen_output_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(50, 440, 191, 181))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.screen_output_7 = QtWidgets.QTextEdit(self.groupBox_5)
        self.screen_output_7.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_7.setFont(font)
        self.screen_output_7.setObjectName("screen_output_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(290, 440, 191, 181))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.screen_output_8 = QtWidgets.QTextEdit(self.groupBox_6)
        self.screen_output_8.setGeometry(QtCore.QRect(0, 30, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output_8.setFont(font)
        self.screen_output_8.setObjectName("screen_output_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.plotWidget = MplWidget(self.tab_4)
        self.plotWidget.setGeometry(QtCore.QRect(0, 0, 531, 601))
        self.plotWidget.setObjectName("plotWidget")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Sensor 2"))
        self.screen_output_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">72</span><span style=\" font-size:24pt; vertical-align:super;\">o</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">62% RH</span></p></body></html>"))
        self.groupBox_26.setTitle(_translate("MainWindow", "Sensor 4"))
        self.screen_output_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">74</span><span style=\" font-size:24pt; vertical-align:super;\">o</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">64% RH</span></p></body></html>"))
        self.groupBox_27.setTitle(_translate("MainWindow", "Sensor 6"))
        self.screen_output_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">76</span><span style=\" font-size:24pt; vertical-align:super;\">o</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">66% RH</span></p></body></html>"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Sensor 1"))
        self.screen_output_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">71</span><span style=\" font-size:24pt; vertical-align:super;\">o</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">61% RH</span></p></body></html>"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Sensor 3"))
        self.screen_output_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">73</span><span style=\" font-size:24pt; vertical-align:super;\">o</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">63% RH</span></p></body></html>"))
        self.groupBox_30.setTitle(_translate("MainWindow", "Sensor 5"))
        self.screen_output_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">75</span><span style=\" font-size:24pt; vertical-align:super;\">o</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">65% RH</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Current"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Sensor 5"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Temperature"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Humidity"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Sensor 1"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Temperature"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Humidity"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Sensor 2"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Temperature"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Humidity"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Sensor 3"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Temperature"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Humidity"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Sensor 4"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Temperature"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Humidity"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Sensor 6"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Temperature"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Humidity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Alarms"))
        self.groupBox.setTitle(_translate("MainWindow", "Sensor 1"))
        self.screen_output_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Error</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sensor 2"))
        self.screen_output_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Errors</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sensor 3"))
        self.screen_output_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">3</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Errors</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sensor 4"))
        self.screen_output_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">4</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Errors</span></p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Sensor 5"))
        self.screen_output_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">5</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Errors</span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Sensor 6"))
        self.screen_output_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">6</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Errors</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Errors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Graphs"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
