# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simple_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_hum_alarm = QtWidgets.QLabel(self.centralwidget)
        self.label_hum_alarm.setGeometry(QtCore.QRect(950, 200, 76, 50))
        self.label_hum_alarm.setObjectName("label_hum_alarm")
        self.label_t_alarm = QtWidgets.QLabel(self.centralwidget)
        self.label_t_alarm.setGeometry(QtCore.QRect(830, 200, 76, 50))
        self.label_t_alarm.setObjectName("label_t_alarm")
        self.label_hum_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_hum_2.setGeometry(QtCore.QRect(730, 200, 55, 50))
        self.label_hum_2.setObjectName("label_hum_2")
        self.label_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_temp.setGeometry(QtCore.QRect(610, 200, 76, 50))
        self.label_temp.setObjectName("label_temp")
        self.pb_select = QtWidgets.QPushButton(self.centralwidget)
        self.pb_select.setGeometry(QtCore.QRect(100, 180, 93, 28))
        self.pb_select.setObjectName("pb_select")
        self.pb_up = QtWidgets.QPushButton(self.centralwidget)
        self.pb_up.setGeometry(QtCore.QRect(100, 250, 93, 28))
        self.pb_up.setObjectName("pb_up")
        self.pb_down = QtWidgets.QPushButton(self.centralwidget)
        self.pb_down.setGeometry(QtCore.QRect(100, 320, 93, 28))
        self.pb_down.setObjectName("pb_down")
        self.label_sensor = QtWidgets.QLabel(self.centralwidget)
        self.label_sensor.setGeometry(QtCore.QRect(520, 200, 51, 50))
        self.label_sensor.setObjectName("label_sensor")
        self.screen_output = QtWidgets.QTextEdit(self.centralwidget)
        self.screen_output.setGeometry(QtCore.QRect(25, 25, 1081, 101))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.screen_output.setFont(font)
        self.screen_output.setObjectName("screen_output")
        self.pb_convertTemp = QtWidgets.QPushButton(self.centralwidget)
        self.pb_convertTemp.setGeometry(QtCore.QRect(600, 260, 93, 28))
        self.pb_convertTemp.setObjectName("pb_convertTemp")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(414, 379, 551, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_logo.setFont(font)
        self.label_logo.setObjectName("label_logo")
        self.led_sensor = QtWidgets.QCheckBox(self.centralwidget)
        self.led_sensor.setGeometry(QtCore.QRect(530, 180, 21, 20))
        self.led_sensor.setText("")
        self.led_sensor.setCheckable(True)
        self.led_sensor.setChecked(True)
        self.led_sensor.setObjectName("led_sensor")
        self.led_temp = QtWidgets.QCheckBox(self.centralwidget)
        self.led_temp.setGeometry(QtCore.QRect(640, 180, 21, 20))
        self.led_temp.setText("")
        self.led_temp.setObjectName("led_temp")
        self.led_hum = QtWidgets.QCheckBox(self.centralwidget)
        self.led_hum.setGeometry(QtCore.QRect(750, 180, 21, 20))
        self.led_hum.setText("")
        self.led_hum.setObjectName("led_hum")
        self.led_t_alarm = QtWidgets.QCheckBox(self.centralwidget)
        self.led_t_alarm.setGeometry(QtCore.QRect(850, 180, 21, 20))
        self.led_t_alarm.setText("")
        self.led_t_alarm.setObjectName("led_t_alarm")
        self.led_h_alarm = QtWidgets.QCheckBox(self.centralwidget)
        self.led_h_alarm.setGeometry(QtCore.QRect(970, 180, 21, 20))
        self.led_h_alarm.setText("")
        self.led_h_alarm.setObjectName("led_h_alarm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_hum_alarm.setText(_translate("MainWindow", "Hum. Alarm"))
        self.label_t_alarm.setText(_translate("MainWindow", "Temp Alarm"))
        self.label_hum_2.setText(_translate("MainWindow", "Humidity"))
        self.label_temp.setText(_translate("MainWindow", "Temperature"))
        self.pb_select.setText(_translate("MainWindow", "Select"))
        self.pb_up.setText(_translate("MainWindow", "Up"))
        self.pb_down.setText(_translate("MainWindow", "Down"))
        self.label_sensor.setText(_translate("MainWindow", "Sensor"))
        self.pb_convertTemp.setText(_translate("MainWindow", "Convert Temp"))
        self.label_logo.setText(_translate("MainWindow", "Super Dooper Sensor Co."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
